version: '3'

services:

  ###
  # LDM
  ###
  ldm:
    build: .
    container_name: ldm
    restart: always
    volumes:
      # change defaults to your liking
      - ./etc/:/home/ldm/etc/
      - ./data/:/home/ldm/var/data/
      - ./queues:/home/ldm/var/queues/
      - ./logs/:/home/ldm/var/logs/
      - ./cron/:/var/spool/cron/
    ports:
      - "388:388"
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    env_file:
      - "compose.env"